### ISSUE TITLE
Full Chinese header causes jekyll-theme-leap-day style to fail.

### ISSUE THREAD

**Issue by zander** [pages-themes/leap-day#1]
See the online (github) pages of my site;
https://blocksizeproposals.github.io/README-cn
or the source;
https://github.com/BlocksizeProposals/BlocksizeProposals.github.io/blob/master/README-cn.md

Notice how on the rendered site (github.io) the headers all have an id="" tag, which in the English version is a sanitized version of the latin1 characters, in the Chinese text the id tag is completely empty.

This breaks the headers-to-the-side feature as you can see. Clicking on each of the links 
on the left side of the screen when looking at this page;
https://blocksizeproposals.github.io/README-cn

has no effect, as each link ends with '#'.

Please notice how the github rendered page does this correctly, it adds the Chinese characters to the URL and escapes them.
So you get something like;
https://github.com/BlocksizeProposals/BlocksizeProposals.github.io/blob/master/README-cn.md#%E6%BF%80%E6%B4%BB%E6%96%B9%E6%B3%95

**Comment by a1ip** [comment]
This `.replace(/[^\w-]+/g,'')` peace of code from [main.js](https://github.com/pages-themes/leap-day/blob/master/assets/js/main.js) file does not work correctly with other languages than English.

I use `.replace(/[^\w\u0410-\u044f-]+/g,'')` for Russian language, as you can see [here](https://codepen.io/a1ip/pen/xXaQQQ?editors=1012).

I don't know the exact range for Chinese characters in Unicode (look [here](https://stackoverflow.com/questions/1366068/whats-the-complete-range-for-chinese-characters-in-unicode) ). So if I use right range for Chinese language code may be like that `.replace(/[^\w\u4e00-\u9eff-]+/g,'')`, you may test it [here](https://codepen.io/a1ip/pen/yzxGaE?editors=1012). Use your own copy of [main.js](https://github.com/pages-themes/leap-day/blob/master/assets/js/main.js) with your own parameters in `.replace()`.
