### ISSUE TITLE
Sorry, think you might need to get this template looked at...

### ISSUE THREAD

**Issue by Andy-ABTec** [pages-themes/leap-day#10]
Apologies - don't know if you've seen these?

https://validator.w3.org/nu/?doc=https%3A%2F%2Fpages-themes.github.io%2Fleap-day%2F#l6c24

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fpages-themes.github.io%2Fleap-day%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by benbalter** [comment]
@Andy-ABTec if you would like to submit a pull request to address any or all of the feedback from the automated tools, you're more than welcome to do so. Without more information, however, I'm afraid we can't act on the feedback at this time.
