### ISSUE TITLE
liquid error: Unknown tag 'seo' included

### ISSUE THREAD

**Issue by estelll** [pages-themes/leap-day#16]
jekyll 3.7.2 | Error:  Liquid syntax error (dirname/_includes/head.html line 5): Unknown tag 'seo' included

I am new to jekyll and I build a site following the tutorial in https://jekyllrb.com/docs/quickstart/. It by default use a gem-based theme and it work well. And then I wanna try regular theme so I copy the directories needed(_includes, _layout,asset and so on) into my site dir. And I delete the command line of 'gem "minima", "~> 2.0"'  in Gemfile and 'theme: minima' in _config.yml as described in https://jekyllrb.com/docs/themes/.
Then I ran jekyll serve but it throws an error above. 

Did I miss something after delete the command lines ?

**Comment by benbalter** [comment]
Please see the [usage instructions](https://github.com/pages-themes/leap-day#usage) to update your Gemfile.
