### ISSUE TITLE
Content in <details> not rendered correctly

### ISSUE THREAD

**Issue by neo** [pages-themes/leap-day#51]
In markdown, we could sometimes have

```md
<details>
<summary>Summary of the details</summary>
- detail 1
- detail 2
- detail 3
</details>
```

rendered like this:

<details>
<summary>Summary of the details</summary>

- detail 1
- detail 2
- detail 3
</details>

However, it's actually rendered and display as plain text... (actually not 100% sure if it's a theme specific problem 😳 )

Thank you!!

**Comment by parkr** [comment]
I think this is how kramdown works – once it enters an HTML tag (in this case, `<details>`) it stops parsing the content as markdown. So you'll need to use `<ul>` manually.

**Comment by neo** [comment]
Thank you for the explanation!

For people who landed here, I managed to make it work by adding `markdown: GFM` to `_config.yml`. While it's working for me, I'm guessing this might have other trade-offs; but might worth trying... 🤔 

(I found out about it from here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll)
