### ISSUE TITLE
GitHub Pages fails to build site: File to import not found or unreadable: leap-day

### ISSUE THREAD

**Issue by ZufengW** [pages-themes/leap-day#53]
I started getting this error today after pushing changes to my leap-day themed GitHub pages site.

Example error:

 * Commit: https://github.com/ZufengW/ZufengW.github.io/commit/9590e6b6b1f87476f449e644933d4389f6927fe3
 * Action: [Page Build](https://github.com/ZufengW/ZufengW.github.io/runs/3148801824)
 * Title: GitHub Pages failed to build your site.
 * Message: Your SCSS file `assets/css/style.scss` has an error on line 1: File to import not found or unreadable: leap-day. Load path: /tmp/jekyll-remote-theme-20210724-6-1uvld1q/_sass.
 * Impact: Cannot update the GitHub pages site.

The commit in this example is a tiny test change that doesn't change the SCSS file. I've done similar commits in the past that worked. But I started noticing this failure today when I pushed to two of my leap-day themed repos.

**Comment by parkr** [comment]
Hi! We're working on it. Please see my comments here: https://github.com/pages-themes/leap-day/issues/54#issuecomment-886957365
