### ISSUE TITLE
Custom CSS does not work anymore

### ISSUE THREAD

**Issue by augustabande** [pages-themes/leap-day#54]
Hi, 

a few days ago our custom CSS stopped working. I made a test with a very easy piece of code and it seems it does not read the CSS after the @ import.

![image](https://user-images.githubusercontent.com/84964508/127014096-2ffe957b-84e1-4b62-8c76-7051eb7b3f0c.png)

**Comment by parkr** [comment]
Hi, #55 now adds `leap-day.scss` so that it works with jekyll-remote-theme. You can use the latest version of this theme by updating it in your _config.yml:

```diff
-theme: jekyll-theme-leap-day
+remote_theme: pages-themes/leap-day@master
```

**Comment by parkr** [comment]
We'll be releasing a new version of GitHub-pages to fix this soon.
