### ISSUE TITLE
Variable Download URLs

### ISSUE THREAD

**Issue by Rictusempra** [pages-themes/leap-day#6]
Helpful for an org

**Comment by benbalter** [comment]
Thanks for this. Do you mind providing a bit more information about what problem you're trying to solve?

**Comment by Rictusempra** [comment]
@benbalter 
check this https://github.com/uMatrix-Rules
the gh page is hosted on https://github.com/uMatrix-Rules/uMatrix-Rules.github.io
And I want to provide download URLs toward files from the rest of repos
