### ISSUE TITLE
External links to ids missing the target

### ISSUE THREAD

**Issue by Andy-ABTec** [pages-themes/leap-day#7]
Just discovered this...

If I open https://pages-themes.github.io/leap-day/ in a browser and click on the "header 2" link on the left hand side everything works as it should, and the page scrolls to a position to show "header 2" just below the banner.

However, if I copy the "header 2" link (https://pages-themes.github.io/leap-day/#header-2)  and paste it into a new browser window or tab "header 2" ends up behind the banner somewhere and you have to scroll up to see it.

Happy Christmas!

Andy B.

**Comment by lambdacasserole** [comment]
Proposed fix in PR #19.
