### ISSUE TITLE
Change "Project maintained by" to something custom?

### ISSUE THREAD

**Issue by MaxValue** [pages-themes/leap-day#8]
In the footer, the theme writes the line "Project maintained by {GithubUsername}".

Would be cool if i could change this line to something like "website maintained by" or something entirely different.

**Comment by Andy-ABTec** [comment]
Editing the text between the \<footer\>\</footer\> tags in /_layouts/index.html works for me...

Take a look at: https://andy-abtec.github.io/tvrename - its a work in progress!

**Comment by MaxValue** [comment]
Yup i realized it in the meantime. Thanks for the info! The documentation is, let's say, very decentralized.
