### ISSUE TITLE
change/set site.github.repository_url 

### ISSUE THREAD

**Issue by Bhlowe** [pages-themes/leap-day#9]
Is there a way to set the github.repository_url in the _config.yml ? Or override the variable?
(I have a main project, and the html in a projectname.github.io page)

I tried in the _config.yml
github.repository_url: https://github.com/user/project
site.github.repository_url: https://github.com/user/project

I haven't used jekyll before, so sorry if this is a simple question.

**Comment by benbalter** [comment]
@Bhlowe Please see https://github.com/pages-themes/leap-day#overriding-github-generated-urls.
